### PR TITLE
Mapping helpers

### PR DESCRIPTION
**Pull request by jacobthill**

### CODE REVIEW

**Review by edsu — APPROVED** [review]
If it's easy to remove the `.DS_Store` files from this PR before merging that would be helpful I think. Otherwise looks good!

**Comment by jacobthill** [comment]
@edsu done, sorry I missed those

**Review by edsu — CHANGES_REQUESTED** [review]
Did you mean to make catalog changes as part of this PR?

**Comment by jacobthill** [comment]
Yes, there was a merge conflict, we need those config changes and I didn't want this PR to remove them

**Comment by jacobthill** [comment]
@edsu are you concerned about this cognitive complexity warning? This is a tool that is used manually and the code is simple enough to be readable, so I'm not personally concerned about it but I can refactor this if you think its a good idea.

**Comment by edsu** [comment]
I'm not concerned myself. I think @suntzu might have a better handle on this since he was recently looking at that configuration?

**Comment by jmartin-sul** [comment]
> I'm not concerned myself. I think @SunTzu might have a better handle on this since he was recently looking at that configuration?

no concern from me, the function code climate is complaining about seems readable enough.

**Pull request merged**
